import { createFileRoute } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { signInWithEmailAndPassword, signOut } from "firebase/auth";
import { doc, getDoc } from "firebase/firestore";
import { Button } from "@/components/ui/button";
import { PageIntro } from "@/components/site/SiteLayout";
import { getFirebaseServices } from "@/lib/firebase-client";
import { isFirebaseConfigured } from "@/lib/firebase";
export const Route = createFileRoute("/admin")({ head: () => ({ meta: [{ title: "Admin access | PK Technology of Engineering" }, { name: "description", content: "Authorized editorial access for PK Technology of Engineering." }, { name: "robots", content: "noindex,nofollow" }, { property: "og:title", content: "Admin access | PK Technology of Engineering" }, { property: "og:description", content: "Authorized editorial access only." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Admin });
function Admin() { const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const services = getFirebaseServices(); if (!services) return; const data = new FormData(e.currentTarget); setBusy(true); setMessage(""); try { const credential = await signInWithEmailAndPassword(services.auth, String(data.get("email")), String(data.get("password"))); const record = await getDoc(doc(services.db, "admins", credential.user.uid)); if (!record.exists() || record.data().active !== true) { await signOut(services.auth); setMessage("This account does not have editorial access."); return; } await signOut(services.auth); setMessage("Your account is authorized. The content dashboard is planned for the next phase."); } catch { setMessage("Could not verify access. Check your details and try again."); } finally { setBusy(false); } } return <><PageIntro eyebrow="Editorial access" title="College administration." description="Authorized access for the PK Technology editorial team." /><section className="page-body"><div className="site-container max-w-2xl"><p className="lead">{isFirebaseConfigured ? "Sign in to verify your editorial access." : "Admin access will be available once the college's Firebase project is connected."}</p>{isFirebaseConfigured && <form className="contact-form" onSubmit={submit}><div className="field full"><label htmlFor="admin-email">Email address</label><input id="admin-email" name="email" type="email" autoComplete="username" required /></div><div className="field full"><label htmlFor="admin-password">Password</label><input id="admin-password" name="password" type="password" autoComplete="current-password" required /></div><div className="field full"><Button type="submit" disabled={busy}>{busy ? "Checking access…" : "Sign in"}</Button></div></form>}{message && <p role="status" className="mt-6 text-ink-soft">{message}</p>}</div></section></>; }
