import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro } from "@/components/site/SiteLayout";
import { gallery, type GalleryItem } from "@/data/site";
export const Route = createFileRoute("/gallery")({ head: () => ({ meta: [{ title: "Gallery | PK Technology of Engineering" }, { name: "description", content: "Explore conceptual visualizations of campus spaces and engineering learning at PK Technology of Engineering." }, { property: "og:title", content: "Gallery | PK Technology of Engineering" }, { property: "og:description", content: "A conceptual look at spaces for learning and discovery." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Gallery });
const categories = ["All", "Campus", "Laboratories", "Learning Spaces"] as const;
function Gallery() { const [category, setCategory] = useState<(typeof categories)[number]>("All"); const [selected, setSelected] = useState<GalleryItem | null>(null); useEffect(() => { if (!selected) return; const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") setSelected(null); }; window.addEventListener("keydown", onKey); document.body.style.overflow = "hidden"; return () => { window.removeEventListener("keydown", onKey); document.body.style.overflow = ""; }; }, [selected]); return <><PageIntro eyebrow="Gallery" title="A closer look at possibility." description="Explore visual concepts of academic spaces, engineering practice, and the campus environment." /><section className="page-body"><div className="site-container"><p className="sample-note">These AI-generated images are conceptual illustrations, not actual photographs of PK Technology of Engineering or its facilities.</p><div role="group" aria-label="Filter gallery" className="gallery-filter">{categories.map(c => <Button key={c} onClick={() => setCategory(c)} variant={category === c ? "default" : "outline"} size="sm" aria-pressed={category === c}>{c}</Button>)}</div><div className="gallery-grid">{gallery.filter(item => category === "All" || item.category === category).map(item => <button className="gallery-item" key={item.id} onClick={() => setSelected(item)} aria-label={`View ${item.title} fullscreen`}><div className="crop"><img src={item.image} alt={item.alt} loading="lazy" width={1200} height={912} /></div><strong>{item.title}</strong><small>{item.category}</small></button>)}</div></div></section>{selected && <div className="lightbox" role="dialog" aria-modal="true" aria-label={selected.title} onClick={() => setSelected(null)}><Button className="lightbox-close" variant="heroOutline" size="icon" aria-label="Close image" onClick={() => setSelected(null)}><X /></Button><img src={selected.image} alt={selected.alt} onClick={e => e.stopPropagation()} /><p>{selected.title} · Conceptual illustration</p></div>}</>; }
